'''
Note: Your Phone and PC should be connected, just make one of them hotspot and connect other with it using wifi, for the program to work properly
'''

import cv2 # importing opencv 

url = 'http://192.168.43.1:8080/video' #IP Address generated by Ip Webcam App for fetching phone visual data 


cap = cv2.VideoCapture(url)  # creating video capture object using  the url



 # Infinite loop starts
while(True):
    ret, frame = cap.read()   #reading the frame using object's function read()

    if frame is not None:           # if frame is not none 
        cv2.imshow('frame',frame)   #showing the frame in our pc in window name frame

    q = cv2.waitKey(1)    # waiting for 1ms to capture any key event
    if q == ord("q"):     
        break             # if q is pressed then it comes of the infinite loop


# after coming out of the loop destroy all the window open for showing video and release the camera source.  
cv2.destroyAllWindows()
cap.release()
